title: PocketSizedGames
author: PocketSizedGames
email: martin.vuminhduc@gmail.com
description: >-
  We create games that you can bring pretty much play anywhere, anytime on your favorite smart phone and smart watch.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "pocketsizedgames.net" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-seo-tag

